global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: WARN
  format: common
api:
  dashboard: true
  insecure: true
ping: {}
accessLog: {}
providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock
    swarmMode: false
    useBindPortIP: false
    network: npm
  file:
    watch: true
    directory: /etc/traefik/config
    debugLogGeneratedTemplate: true
entryPoints:
  http:
    address: :80
    transport: 
      respondingTimeouts: 
        readTimeout: 0
  https:
    address: :443
    transport: 
      respondingTimeouts: 
        readTimeout: 0    
  samba139:
    address: :139
    transport: 
      respondingTimeouts: 
        readTimeout: 0    
  samba445:
    address: :445
    transport: 
      respondingTimeouts: 
        readTimeout: 0    
experimental:
  localPlugins:
    example:
      moduleName: github.com/traefik/plugindemo
    rewritebody:
      moduleName: github.com/packruler/rewrite-body
